export const PROFILES = [
  {
    id: "0",
    imgURL: "/images/professor.jpg",
    name: "Choi.J.R",
    position: "Professor",
    email: "aaa@naver.com",
  },
  {
    id: "1",
    imgURL: "/images/woman.jpg",
    name: "Kim.E.S",
    position: "Graduate",
    email: "aaa@naver.com",
  },
  {
    id: "2",
    imgURL: "/images/woman.jpg",
    name: "kim",
    position: "Graduate",
    email: "bbb@naver.com",
  },
  {
    id: "3",
    imgURL: "/images/woman.jpg",
    name: "choi",
    position: "Graduate",
    email: "ccc@gmail.com",
  },
  {
    id: "4",
    imgURL: "/images/woman.jpg",
    name: "Sung.J.Y",
    position: "Student",
    email: "ddd@gmail.com",
  },
  {
    id: "5",
    imgURL: "/images/woman.jpg",
    name: "Yun.U.B",
    position: "Student",
    email: "ddd@gmail.com",
  },
  {
    id: "6",
    imgURL: "/images/woman.jpg",
    name: "Lee.H.A",
    position: "Student",
    email: "ddd@gmail.com",
  },
  {
    id: "7",
    imgURL: "/images/woman.jpg",
    name: "Park.M.R",
    position: "Student",
    email: "ddd@gmail.com",
  },
  {
    id: "8",
    imgURL: "/images/woman.jpg",
    name: "Shim.Y.E",
    position: "Student",
    email: "ddd@gmail.com",
  },
  {
    id: "13",
    imgURL: "/images/woman.jpg",
    name: "Lee.T.K",
    position: "Student",
    email: "ddd@gmail.com",
  },
  {
    id: "14",
    imgURL: "/images/woman.jpg",
    name: "Shin.H.R",
    position: "Student",
    email: "ddd@gmail.com",
  },
  {
    id: "9",
    position: "Student",
  },
  {
    id: "10",
    position: "Graduate",
  },
  {
    id: "11",
    imgURL: "/images/professor.jpg",
    name: "Lee.S.T",
    position: "Professor",
    email: "aaa@naver.com",
  },
  {
    id: "12",
    imgURL: "/images/professor.jpg",
    name: "Shin S.A",
    position: "Professor",
    email: "aaa@naver.com",
  },
];
